#!/bin/sh

set -e

CFLAGS="$(dpkg-buildflags --get CFLAGS)"
CPPFLAGS="$(dpkg-buildflags --get CPPFLAGS)"
LDFLAGS="$(dpkg-buildflags --get LDFLAGS)"

cd tests

export VECTORS='vectors'
EXIT=0

for f in $(find . -maxdepth 1 -type f -executable | sort) ; do
    echo "Testing: $(basename "$f")"
    chronic "$f" || EXIT=1
done

for f in $(find . -maxdepth 1 -type f -name '*.c' | sort) ; do
    BN="$(basename "$f")"
    echo "Compiling: $BN"
    PROG="${BN%%.c}"
    cc $CFLAGS $CPPFLAGS $LDFLAGS "$f" -o "$PROG" -ljose -ljansson
    echo "Testing: $PROG"
    chronic "./$PROG" || EXIT=1
done

exit "$EXIT"
